module.exports = {
    book:                           'Book',
    chapter:                        'Chap',
    verse:                          'Vs',
    book_chapter_verse:             'Bk/Ch/Vs',
    nt_word_position:               'NT Word position',
    book_word_position:             'Book Word position',
    english:                        'English',
    greek:                          'Greek',
    letters:                        '# letters in word',
    word_total_value:               'Word total value',
    verse_letters:                  'Verse #letters',
    verse_words:                    'Verse #words',
    verse_total_value:              'Verse total value',
    chapter_letters:                'Chapter #letters',
    chapter_words:                  'Chapter #words',
    chapter_total_value:            'Chapter total value',
    book_letters:                   'Book #letters',
    book_words:                     'Book #words',
    book_total_value:               'Book total value',
    cumulative_book_letters:        'Cumulative Book #letters',
    cumulative_book_words:          'Cumulative Book #words',
    cumulative_book_total_value:    'Cumulative Book total value'
}
